### ISSUE TITLE
Implement better logging, on both sides

### ISSUE THREAD

**Issue by jirkadanek** [msgqe/djtests-agent#1]
Current, ridiculously unreadable log

```
[sh, -c, java -jar cli-qpid-jms/target/cli-qpid-jms-1.2.2-SNAPSHOT-LATEST.jar sender --broker-uri 'failover:(amqp://127.0.0.1:1883)?jms.connectTimeout=1&failover.maxReconnectAttempts=1&failover.startupMaxReconnectAttempts=1' --log-msgs dict --timeout 2]
25979
10:24:02,615 ERROR Failed to connect after: 1 attempt(s)
10:24:02,620 ERROR ExceptionListener error detected! 
javax.jms.JMSException: Timed out while waiting to connect
Timed out while waiting to connect
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.onAsyncException(JmsConnection.java:1390)
	at org.apache.qpid.jms.JmsConnection.onProviderException(JmsConnection.java:1374)
	at org.apache.qpid.jms.JmsConnection.onConnectionFailure(JmsConnection.java:1242)
	at org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:732)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Timed out while waiting to connect
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)
	at org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)
	... 7 more
javax.jms.JMSException: Timed out while waiting to connect
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:613)
	at org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:597)
	at org.apache.qpid.jms.JmsConnection.createJmsConnection(JmsConnection.java:512)
	at org.apache.qpid.jms.JmsConnection.createSession(JmsConnection.java:297)
	at com.redhat.mqe.lib.CoreClient.createSession(CoreClient.java:120)
	at com.redhat.mqe.lib.SenderClient.startClient(SenderClient.java:80)
	at com.redhat.mqe.lib.Main.main(Main.java:50)
	at com.redhat.mqe.jms.Main.main(Main.java:80)
	at com.redhat.mqe.jms.Main.main(Main.java:84)
Caused by: java.io.IOException: Timed out while waiting to connect
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)
	at org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
{}
java.io.IOException: Timed out while waiting to connect
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)
	at org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10:24:02,621 ERROR Error while creating session! Timed out while waiting to connect
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And in test

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/jdanek/Work/repos/djtests, inifile: pytest.ini
plugins: xdist-1.22.0, sugar-0.9.1, forked-0.2
collected 1 item
test_JAMQClients111Tests.py cli: "aac1"
type: "sender"
options: "--broker-uri"
options: "\'failover:(amqp://127.0.0.1:1883)?jms.connectTimeout=1&failover.maxReconnectAttempts=1&failover.startupMaxReconnectAttempts=1\'"
options: "--log-msgs"
options: "dict"
options: "--timeout"
options: "2"
wrapperOptions {
  c_killtime {
    value: 30
  }
}

got rep, status 0
cli_id {
  pid: 25979
}

got rep, status 0
lines: "10:24:02,615 ERROR Failed to connect after: 1 attempt(s)"

('cannot parse ', u'10:24:02,615 ERROR Failed to connect after: 1 attempt(s)')
got rep, status 0
lines: "10:24:02,620 ERROR ExceptionListener error detected! "

('cannot parse ', u'10:24:02,620 ERROR ExceptionListener error detected! ')
got rep, status 0
stderr: "javax.jms.JMSException: Timed out while waiting to connect"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.onAsyncException(JmsConnection.java:1390)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.onProviderException(JmsConnection.java:1374)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.onConnectionFailure(JmsConnection.java:1242)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:732)"

got rep, status 0
stderr: "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)"

got rep, status 0
stderr: "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)"

got rep, status 0
stderr: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)"

got rep, status 0
stderr: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)"

got rep, status 0
stderr: "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)"

got rep, status 0
stderr: "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)"

got rep, status 0
stderr: "\tat java.lang.Thread.run(Thread.java:745)"

got rep, status 0
stderr: "Caused by: java.io.IOException: Timed out while waiting to connect"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)"

got rep, status 0
stderr: "\t... 7 more"

got rep, status 0
stderr: "javax.jms.JMSException: Timed out while waiting to connect"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:613)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.createResource(JmsConnection.java:597)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.createJmsConnection(JmsConnection.java:512)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.JmsConnection.createSession(JmsConnection.java:297)"

got rep, status 0
stderr: "\tat com.redhat.mqe.lib.CoreClient.createSession(CoreClient.java:120)"

got rep, status 0
stderr: "\tat com.redhat.mqe.lib.SenderClient.startClient(SenderClient.java:80)"

got rep, status 0
stderr: "\tat com.redhat.mqe.lib.Main.main(Main.java:50)"

got rep, status 0
stderr: "\tat com.redhat.mqe.jms.Main.main(Main.java:80)"

got rep, status 0
stderr: "\tat com.redhat.mqe.jms.Main.main(Main.java:84)"

got rep, status 0
stderr: "Caused by: java.io.IOException: Timed out while waiting to connect"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)"

got rep, status 0
stderr: "\tat org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)"

got rep, status 0
stderr: "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)"

got rep, status 0
lines: "Timed out while waiting to connect"

('cannot parse ', u'Timed out while waiting to connect')
got rep, status 0
lines: "{}"

got rep, status 0
lines: "java.io.IOException: Timed out while waiting to connect"

('cannot parse ', u'java.io.IOException: Timed out while waiting to connect')
got rep, status 0
lines: "\tat org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)"

('cannot parse ', u'\tat org.apache.qpid.jms.provider.amqp.AmqpProvider.connect(AmqpProvider.java:233)')
got rep, status 0
lines: "\tat org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)"

('cannot parse ', u'\tat org.apache.qpid.jms.provider.failover.FailoverProvider$16.run(FailoverProvider.java:706)')
got rep, status 0
lines: "\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)"

('cannot parse ', u'\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)')
got rep, status 0
lines: "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)"

('cannot parse ', u'\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)')
got rep, status 0
lines: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)"

('cannot parse ', u'\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)')
got rep, status 0
lines: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)"

('cannot parse ', u'\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)')
got rep, status 0
stderr: "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)"

got rep, status 0
lines: "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)"

('cannot parse ', u'\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)')
got rep, status 0
stderr: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)"

got rep, status 0
lines: "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)"

('cannot parse ', u'\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)')
got rep, status 0
stderr: "\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)"

got rep, status 0
lines: "\tat java.lang.Thread.run(Thread.java:745)"

('cannot parse ', u'\tat java.lang.Thread.run(Thread.java:745)')
got rep, status 0
stderr: "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)"

got rep, status 0
lines: "10:24:02,621 ERROR Error while creating session! Timed out while waiting to connect"

('cannot parse ', u'10:24:02,621 ERROR Error while creating session! Timed out while waiting to connect')
got rep, status 0
stderr: "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)"

got rep, status 0
stderr: "\tat java.lang.Thread.run(Thread.java:745)"

got rep, status 1
status: 1

None
None
.

=========================== 1 passed in 2.02 seconds ===========================
Process finished with exit code 0
```

**Comment by jirkadanek** [comment]
* distinguish stdout, stderr, message, error messsage
** o>, e>, m>, something like this, start of every line, will have to try and see how it looks like
* command should be copyable
* possibly use java log format to file, for ideolog, https://plugins.jetbrains.com/plugin/9746-ideolog

**Comment by jirkadanek** [comment]
It should be possible to identify which command is which, possibly use numbers, like client pid prefix, and colors to distinguish stdout and stderr

**Comment by jirkadanek** [comment]
* [ ] do not print entire received message if it is over certain size
* [ ] instead, print beginning, end and hash
