### ISSUE TITLE
Server startup sometimes fails after previous kill

### ISSUE THREAD

**Issue by jirkadanek** [msgqe/djtests-agent#5]
```
2018-04-07 18:53:02,706 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 2093c7f5-3a84-11e8-9495-f2586be15442
KILLING
Exception in thread "Thread-2" java.io.UncheckedIOException: java.io.IOException: Stream closed
	at java.base/java.io.BufferedReader$1.hasNext(BufferedReader.java:577)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at BrkService.lambda$startUp$1(BrkMain.java:64)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at java.base/java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
	... 5 more
Error: There is another process using the server at /home/jdanek/Downloads/AMQ7/7.1.0/cr2.2/amq-broker-7.1.0/i0/lock. Cannot start the process!
```

**Comment by jirkadanek** [comment]
Either wait a while before starting again, or wait until it is really dead (blocking kill, on the client side), or check that shutdown is done before starting again (on the agent side), or wait after start and make sure it stayed up.

Any implications if the agent was to manage multiple brokers in the future? Question is, should it? Maybe orchestration should be done by the client.

**Comment by jirkadanek** [comment]
As a workaround, I am adding the check regarding broker process, will wait for it to die when asked to send a kill signal. This has impacts on tests. They may not expect this. Most likely it does not matter, though, and this may remain permanent.
