### ISSUE TITLE
Tests should not get stuck forever when agent becomes unavailable

### ISSUE THREAD

**Issue by jirkadanek** [msgqe/djtests-agent#9]
```
                except:
                    # If we hit any problems here, clean up the connection.
                    # Then, reraise so that we can handle the actual exception.
                    low_conn.close()
                    raise
    
        except (ProtocolError, socket.error) as err:
>           raise ConnectionError(err, request=request)
E           ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

/usr/local/lib/python2.7/dist-packages/requests/adapters.py:490: ConnectionError
[14:47:58][Step 6/8] generated.test_JAMQMsgSelector777Tests.JAMQMsgSelector777Tests.test_boolean_dnf (running for 1h:18m:25s)
[14:48:00][Step 6/8] E0417 14:48:00.576820    3913 portforward.go:271] error creating error stream for port 8161 -> 8161: Timeout occured
[14:48:22][Step 6/8] E0417 14:48:21.966847    3913 portforward.go:271] error creating error stream for port 8161 -> 8161: Timeout occured
[14:48:28][Step 6/8] E0417 14:48:28.392614    3913 portforward.go:271] error creating error stream for port 8161 -> 8161: Timeout occured
```

 This build is hanging. Last message from the agent was received on: 17 Apr 18 14:48 (1h:21m ago)

**Comment by jirkadanek** [comment]
<details><summary>client-agent</summary>
<code>
{'address': None, 'annotations': None, 'content': None, 'content_encoding': 'None', 'content_type': 'text/plain', 'correlation_id': None, 'creation_time': 0.000000, 'delivery_count': 0, 'durable': False, 'expiration': 0, 'first_acquirer': False, 'group_id': None, 'group_sequence': 0, 'id': None, 'inferred': False, 'instructions': None, 'priority': 4, 'properties': {'a': True}, 'reply_to': None, 'reply_to_group_id': None, 'subject': None, 'ttl': 0, 'user_id': ''}
ERROR {'cause' :'Connection error: amqp:connection:forced ...'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
ERROR {'cause' :'Transport error: proton:io - recv: Connection refused'}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, a~True, --msg-property, b~True, --address, unknowntestQdbS8GW]
26515
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976436964, 'content-type': None, 'id': 'djtests-agent-385-61-40124-1523976436688-1:1:1:1:1', 'reply-to': None, 'properties': {'a': True, 'b': True}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, a~True, --address, unknowntestQdbS8GW]
26545
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976437846, 'content-type': None, 'id': 'djtests-agent-385-61-41034-1523976437631-1:1:1:1:1', 'reply-to': None, 'properties': {'a': True}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, b~True, --address, unknowntestQdbS8GW]
26574
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976438665, 'content-type': None, 'id': 'djtests-agent-385-61-43998-1523976438458-1:1:1:1:1', 'reply-to': None, 'properties': {'b': True}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, a~False, --address, unknowntestQdbS8GW]
26603
[python2, cli_proton_python/receiver.py, --log-msgs, dict, --count, 0, --timeout, 2, --broker, amqp://127.0.0.1:5672/unknowntestPZr45T3]
26631
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976439592, 'content-type': None, 'id': 'djtests-agent-385-61-40472-1523976439317-1:1:1:1:1', 'reply-to': None, 'properties': {'a': False}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, b~False, --address, unknowntestQdbS8GW]
26640
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976440462, 'content-type': None, 'id': 'djtests-agent-385-61-40332-1523976440247-1:1:1:1:1', 'reply-to': None, 'properties': {'b': False}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, a~True, --msg-property, b~False, --address, unknowntestQdbS8GW]
26669
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976441287, 'content-type': None, 'id': 'djtests-agent-385-61-35526-1523976441096-1:1:1:1:1', 'reply-to': None, 'properties': {'a': True, 'b': False}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, sender, --log-msgs, dict, --msg-property, a~False, --msg-property, b~True, --address, unknowntestQdbS8GW]
26698
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976442159, 'content-type': None, 'id': 'djtests-agent-385-61-38525-1523976441920-1:1:1:1:1', 'reply-to': None, 'properties': {'a': False, 'b': True}}
[java, -jar, cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar, receiver, --log-msgs, dict, --count, 0, --msg-selector, a AND b, --timeout, 2, --address, unknowntestQdbS8GW]
26727
{'address': 'unknowntestQdbS8GW', 'group-id': None, 'subject': None, 'user-id': None, 'correlation-id': None, 'content-encoding': None, 'priority': 4, 'type': None, 'ttl': 0, 'absolute-expiry-time': 0, 'content': None, 'redelivered': False, 'reply-to-group-id': None, 'durable': True, 'group-sequence': 0, 'creation-time': 1523976436964, 'content-type': None, 'id': 'djtests-agent-385-61-40124-1523976436688-1:1:1:1:1', 'reply-to': None, 'properties': {'a': True, 'b': True}}
</code>
</details>

<details><summary>broker-agent</summary>
<code>
2018-04-17 14:47:10,358 INFO  [org.apache.activemq.artemis] AMQ241001: HTTP Server started at http://0.0.0.0:8161
2018-04-17 14:47:10,358 INFO  [org.apache.activemq.artemis] AMQ241002: Artemis Jolokia REST API available at http://0.0.0.0:8161/console/jolokia
2018-04-17 14:47:10,358 INFO  [org.apache.activemq.artemis] AMQ241004: Artemis Console available at http://0.0.0.0:8161/console
2018-04-17 14:47:16,995 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 392a842f-424e-11e8-9266-0a580af40059
2018-04-17 14:47:16,996 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 392a842f-424e-11e8-9266-0a580af40059
2018-04-17 14:47:16,996 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-40124-1523976436688-1:1:-1
2018-04-17 14:47:16,996 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-40124-1523976436688-1:1:-1
2018-04-17 14:47:17,865 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 39b49bc2-424e-11e8-9266-0a580af40059
2018-04-17 14:47:17,866 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 39b49bc2-424e-11e8-9266-0a580af40059
2018-04-17 14:47:17,866 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-41034-1523976437631-1:1:-1
2018-04-17 14:47:17,866 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-41034-1523976437631-1:1:-1
2018-04-17 14:47:18,680 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 3a325745-424e-11e8-9266-0a580af40059
2018-04-17 14:47:18,681 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 3a325745-424e-11e8-9266-0a580af40059
2018-04-17 14:47:18,681 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-43998-1523976438458-1:1:-1
2018-04-17 14:47:18,681 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-43998-1523976438458-1:1:-1
2018-04-17 14:47:19,611 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 3ab67b68-424e-11e8-9266-0a580af40059
2018-04-17 14:47:19,612 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 3ab67b68-424e-11e8-9266-0a580af40059
2018-04-17 14:47:19,612 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-40472-1523976439317-1:1:-1
2018-04-17 14:47:19,612 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-40472-1523976439317-1:1:-1
2018-04-17 14:47:20,483 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 3b43ee5d-424e-11e8-9266-0a580af40059
2018-04-17 14:47:20,483 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 3b43ee5d-424e-11e8-9266-0a580af40059
2018-04-17 14:47:20,483 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-40332-1523976440247-1:1:-1
2018-04-17 14:47:20,483 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-40332-1523976440247-1:1:-1
2018-04-17 14:47:21,303 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 3bc35790-424e-11e8-9266-0a580af40059
2018-04-17 14:47:21,303 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 3bc35790-424e-11e8-9266-0a580af40059
2018-04-17 14:47:21,303 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-35526-1523976441096-1:1:-1
2018-04-17 14:47:21,303 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-35526-1523976441096-1:1:-1
2018-04-17 14:47:22,182 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 3c42e7d3-424e-11e8-9266-0a580af40059
2018-04-17 14:47:22,182 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 3c42e7d3-424e-11e8-9266-0a580af40059
2018-04-17 14:47:22,183 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session ID:djtests-agent-385-61-38525-1523976441920-1:1:-1
2018-04-17 14:47:22,183 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session ID:djtests-agent-385-61-38525-1523976441920-1:1:-1
Exception in thread "Thread-16" java.io.UncheckedIOException: java.io.IOException: Stream closed
        at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at BrkService.lambda$startUp$1(BrkMain.java:65)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
        ... 5 more
KILLING
KILLING
KILLING
</code>
</details>
